"""Run the agent graph once on a scratch copy of the database and write the transcript as markdown.

Run:  python -m runners.example_run [--restaurant r_pho_house] [--out docs/example-run.md]

The real database is never touched: the run happens on a temporary copy. The owner's decision is
scripted (see DECISIONS) so the transcript is reproducible.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import tempfile
import time
from pathlib import Path
from typing import Any

from growth.data import queries as q
from growth.graph import Command, build_graph, new_thread, pending_approval
from growth.state import Recommendation
from growth.tools import listing as listing_tool

# Scripted owner decisions per restaurant: approve by kind, reject by kind with a reason.
DECISIONS: dict[str, dict[str, Any]] = {
    "r_pho_house": {
        "approve": ["add_descriptions", "delivery_quality"],
        "reject": {"price_cut": "We raised prices last month to cover rent. Not cutting this quarter."},
    },
}


def _card(r: Recommendation, n: int, hidden: list[Recommendation]) -> list[str]:
    i = r.impact
    out = [
        f"#### Card {n}: {r.title}",
        "",
        f"`{r.id}` · agent **{r.agent}** · kind `{r.kind}` · confidence **{r.confidence}**"
        + (f" · variant *{r.variant_label}*" if r.variant_label else ""),
        "",
        f"**Why:** {r.rationale}",
        "",
        f"**Action:** {r.action}",
        "",
        "**Evidence**",
        "",
    ]
    out += [f"- `{e.kind}` `{e.ref}`: {e.detail}" for e in r.evidence[:4]]
    if len(r.evidence) > 4:
        out.append(f"- … and {len(r.evidence) - 4} more")
    out += [
        "",
        f"**Impact:** +{i.orders_per_week} orders/week, +€{i.gmv_eur_per_week:,.2f} GMV/week, "
        f"**€{i.jet_revenue_eur_per_week:,.2f}/week to JET**",
        "",
        f"> {i.formula}",
        "",
    ]
    if r.lever_changes:
        out += ["**Lever changes (for the ML model)**", ""]
        out += [f"- `{lc.lever}`: {lc.before} → {lc.after} ({lc.note})" for lc in r.lever_changes]
        out.append("")
    if r.patch:
        out += [f"**Listing patch:** {len(r.patch)} operation(s), first: `{json.dumps(r.patch_ops()[0])}`", ""]
    else:
        out += ["**Listing patch:** none, advice only", ""]
    if hidden:
        out += ["**Other variants (kept in state for the optimiser, not shown to the owner)**", ""]
        out += [
            f"- *{h.variant_label}*: €{h.impact.jet_revenue_eur_per_week:,.2f}/week to JET, "
            f"`{h.lever_changes[0].lever}` → {h.lever_changes[0].after}"
            for h in hidden
        ]
        out.append("")
    return out


def run(restaurant_id: str, out_path: Path, db_path: Path = q.DB_PATH) -> None:
    decision_spec = DECISIONS[restaurant_id]
    with tempfile.TemporaryDirectory() as tmp:
        db = Path(tmp) / "jet.duckdb"
        shutil.copy(db_path, db)
        graph = build_graph(db)
        config = new_thread()
        md: list[str] = []

        con = q.connect(db)  # read-write, same config as the graph's connection
        restaurant = q.get_restaurant(con, restaurant_id)
        before = listing_tool.get_listing(con, restaurant_id)
        weekly = q.weekly_summary(con, restaurant_id)

        md += [
            f"# Example run: {restaurant['name']}",
            "",
            "Generated by `python -m runners.example_run` on a scratch copy of the database. "
            "The owner's decision is scripted so the run is reproducible.",
            "",
            "- **LLM wording:** "
            + (
                "Anthropic"
                if os.environ.get("ANTHROPIC_API_KEY")
                else "no Anthropic key set, so card titles and descriptions use the template fallback"
            ),
            "- **Review tagging:** TypeSafe Jev (cached answers are reused)",
            "",
            "## 1. Start",
            "",
            "```python",
            f'graph.stream({{"restaurant_id": "{restaurant_id}"}}, config, stream_mode="updates")',
            "```",
            "",
            f"**{restaurant['name']}**: {restaurant['cuisine']}, {restaurant['city']}, "
            f"{restaurant['delivery_model'].replace('_', ' ')}, {restaurant['commission_rate']:.0%} commission, "
            f"rating {restaurant['rating']}. "
            f"{weekly['orders_per_week']:.0f} orders/week, €{weekly['gmv_eur_per_week']:,.0f} GMV/week, "
            f"basket €{weekly['avg_basket_eur']:.2f}.",
            "",
            "## 2. Progress stream",
            "",
            "| # | Node | Finished after | Output |",
            "|---|---|---|---|",
        ]

        t0 = time.perf_counter()
        for n, update in enumerate(graph.stream({"restaurant_id": restaurant_id}, config, stream_mode="updates"), 1):
            for node, payload in update.items():
                elapsed = f"{time.perf_counter() - t0:.2f}s"
                if node == "__interrupt__":
                    what = "paused for the owner's decision"
                elif node == "load_context":
                    what = f"listing with {len(payload['context']['listing']['menu'])} dishes"
                elif node in ("reviews", "menu", "pricing", "promo_ads"):
                    recs = payload["recommendations"][node]
                    groups = {r.variant_group for r in recs if r.variant_group}
                    what = f"{len(recs)} card(s)" + (f", {len(groups)} variant group(s)" if groups else "")
                elif node == "impact":
                    what = "impact estimated for every card"
                elif node == "rank":
                    what = f"{len(payload['ranked'])} card(s) shown to the owner, best first"
                else:
                    what = ""
                md.append(f"| {n} | `{node}` | {elapsed} | {what} |")

        cards = pending_approval(graph, config)
        all_recs = [r for recs in graph.get_state(config).values["recommendations"].values() for r in recs]
        md += ["", "## 3. Cards waiting for approval", ""]
        for n, card in enumerate(cards, 1):
            hidden = [
                r for r in all_recs if card.variant_group and r.variant_group == card.variant_group and r.id != card.id
            ]
            md += _card(card, n, hidden)

        by_kind = {c.kind: c.id for c in cards}
        decision = {
            "approve": [by_kind[k] for k in decision_spec["approve"] if k in by_kind],
            "reject": {by_kind[k]: reason for k, reason in decision_spec["reject"].items() if k in by_kind},
        }
        md += [
            "## 4. Owner's decision",
            "",
            "```python",
            f"graph.invoke(Command(resume={json.dumps(decision, indent=4)}), config)",
            "```",
            "",
        ]
        final = graph.invoke(Command(resume=decision), config)

        after = listing_tool.get_listing(con, restaurant_id)
        md += ["## 5. Result", "", "**Approvals**", ""]
        md += [f"- `{rid}`: {'approved' if ok else 'rejected'}" for rid, ok in final["approvals"].items()]
        md += ["", "**Rejection reasons** (kept in state; the optimiser will use them as constraints)", ""]
        md += [f'- `{rid}`: "{reason}"' for rid, reason in final["rejection_reasons"].items()] or ["- none"]
        md += ["", "**Applied listing changes**", ""]
        for a in final["applied"]:
            md.append(f"- `{a.change_id}` from `{a.recommendation_id}`: {len(a.patch)} operation(s)")
        if not final["applied"]:
            md.append("- none")
        md += ["", "**Listing diff**", "", "```json", json.dumps(listing_tool.diff(before, after), indent=2), "```", ""]
        md += ["**Errors:** " + ("; ".join(final["errors"]) if final["errors"] else "none"), ""]
        s = final["summary"]
        md += [
            "## 6. Summary",
            "",
            f"> {s.text}",
            "",
            f"Approved {s.approved}, rejected {s.rejected}. Total: +{s.total.orders_per_week} orders/week, "
            f"+€{s.total.gmv_eur_per_week:,.2f} GMV/week, €{s.total.jet_revenue_eur_per_week:,.2f}/week to JET.",
            "",
            "Every applied change is in `change_log` with its before-image and can be reverted with "
            "`growth.tools.listing.revert(con, change_id)`.",
            "",
        ]
        con.close()

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(md))
    print(f"Wrote {out_path}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--restaurant", default="r_pho_house", choices=sorted(DECISIONS))
    ap.add_argument("--out", default="docs/example-run.md")
    args = ap.parse_args()
    run(args.restaurant, Path(args.out))


if __name__ == "__main__":
    main()
